server:
  port: ${PORT:8080}

spring:
  application:
    name: culo-server

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html

culo:
  cors:
    allowed-origins:
      - http://localhost:*
      - http://127.0.0.1:*
      - https://breimato.es
      - https://www.breimato.es
  room:
    ttl-hours: 2

logging:
  level:
    com.breixo.culo: DEBUG
